[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
runner = "run-qemu"
rustflags = ["-Clink-arg=-Tcrates/kernel/lds/qemu.lds"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
