[package]
name = "devicetree"
version = "0.1.0"
description = "Implementation of the Flattenede Device Tree format"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"

[dependencies]
memchr = { version = "2.3.4", default-features = false }
