[package]
name = "common"
version = "0.1.0"
description = "Commonly used components that are used across various crates."
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"

[dependencies]
